from matplotlib.patches import Circle
import matplotlib.pyplot as plt

plt.plot([0, 1, 1], [-1, -1, -2], 'k')
plt.plot([1, 2, 2], [-2, -2, -3], 'k')
plt.plot([3, 0, 0], [0, 0, -1], 'k')
plt.plot([3, 5, 5], [0, 0, -1], 'k')
plt.plot([5, 4, 4], [-1, -1, -2], 'k')
plt.plot([5, 9, 9], [-1, -1, -2], 'k')
plt.plot([7, 6, 6], [-3, -3, -4], 'k')
plt.plot([7, 8, 8], [-3, -3, -4], 'k')
plt.plot([9, 7, 7], [-2, -2, -3], 'k')
plt.text(0, -1, "B", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(1, -2, "C", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(2, -3, "D", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(3, 0, "A", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(4, -2, "F", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(5, -1, "E", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(6, -4, "J", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(7, -3, "H", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(8, -4, "I", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(9, -2, "G", color = "k", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.axis('scaled')
plt.axis('equal')

plt.axis('off')
plt.tight_layout()
fig = plt.gcf()
fig.canvas.set_window_title('T2')
plt.show()
