from matplotlib.patches import Circle
import matplotlib.pyplot as plt

plt.plot([1, 0, 0], [-2, -2, -3], 'k')
plt.plot([1, 2, 2], [-2, -2, -3], 'k')
plt.plot([3, 1, 1], [-1, -1, -2], 'k')
plt.plot([3, 4, 4], [-1, -1, -2], 'k')
plt.plot([5, 3, 3], [0, 0, -1], 'k')
plt.plot([5, 9, 9], [0, 0, -1], 'k')
plt.plot([7, 6, 6], [-2, -2, -3], 'k')
plt.plot([7, 8, 8], [-2, -2, -3], 'k')
plt.plot([9, 7, 7], [-1, -1, -2], 'k')
plt.plot([9, 12, 12], [-1, -1, -2], 'k')
plt.plot([10, 11, 11], [-3, -3, -4], 'k')
plt.plot([12, 10, 10], [-2, -2, -3], 'k')
plt.plot([12, 14, 14], [-2, -2, -3], 'k')
plt.plot([14, 13, 13], [-3, -3, -4], 'k')
plt.text(0, -3, "0", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(1, -2, "1", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(2, -3, "2", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(3, -1, "3", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(4, -2, "4", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(5, 0, "5", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(6, -3, "6", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(7, -2, "7", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(8, -3, "8", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(9, -1, "10", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(10, -3, "11", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(11, -4, "15", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(12, -2, "21", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(13, -4, "28", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.text(14, -3, "30", size=15, ha="center", va="center", bbox=dict(boxstyle="circle", ec="k", fc="w"))
plt.axis('scaled')
plt.axis('equal')

plt.axis('off')
plt.tight_layout()
fig = plt.gcf()
fig.canvas.set_window_title('1')
plt.show()
